const PROFILE_TAB_LABELS = {
  EVENT_AND_WORKOUT_STATS: 'EVENTS & WORKOUT STATS',
  CHALLENGE_WORKOUT_LOGS: 'Challenge Workout Logs',
  CHALLENGE_BADGES: 'Challenge Badges',
  JOIN_CHALLENGES_EARN_BADGES: 'Join challenges to earn badges',
  ALL_TIME_CHALLENGES: 'CHALLENGES',
  YTD_EVENTS: 'EVENTS (YTD)',
  MTD_EVENTS: 'EVENTS (MTD)',
};

export {PROFILE_TAB_LABELS};
