'use strict';

import {StyleSheet, Dimensions} from 'react-native';

export const RWBColors = {
  white: 'white',
  whiteOpacity85: 'rgba(255, 255, 255, 0.85)',
  navy: '#041E42',
  magenta: '#BF0D3E',
  grey: '#63666A',
  grey80: '#828588',
  grey40: '#C1C2C3',
  grey20: '#E0E0E1',
  grey8: '#F3F3F3',
  grey5: '#F7F7F8',
  blue: '#3367b0',
  greySilver: '#c8c8c8',
  gold: '#f0c534',
};

export default StyleSheet.create({
  // Typography Styles
  title: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 16,
    lineHeight: 18,
    color: RWBColors.white,
  },
  titleSubheader: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 9,
    lineHeight: 11,
    color: RWBColors.white,
  },
  h1: {
    fontFamily: 'ChangaOne-Italic',
    fontSize: 20,
    lineHeight: 22,
    color: RWBColors.navy,
    paddingBottom: 4,
  },
  h2: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 14,
    lineHeight: 18,
    color: RWBColors.navy,
  },
  h3: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 12,
    lineHeight: 16,
    color: RWBColors.navy,
  },
  h4: {
    fontFamily: 'OpenSans-Extrabold',
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: 0.2,
  },
  h5: {
    fontFamily: 'OpenSans-SemiboldItalic',
    fontSize: 12,
    lineHeight: 16,
    color: RWBColors.magenta,
  },
  h6: {
    fontFamily: 'OpenSans',
    fontSize: 10,
    lineHeight: 14,
    color: RWBColors.grey,
    letterSpacing: 0.2,
    paddingBottom: 2,
  },
  h7: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 12,
    lineHeight: 16,
    color: RWBColors.magenta,
  },
  eventCardTitle: {
    fontFamily: 'ChangaOne-Italic',
    fontSize: 14,
    color: RWBColors.navy,
  },
  eventListTitle: {
    fontFamily: 'ChangaOne-Italic',
    fontSize: 14,
    color: RWBColors.navy,
  },
  bodyCopy: {
    fontFamily: 'OpenSans',
    fontSize: 12,
    lineHeight: 16,
    color: RWBColors.grey,
    paddingBottom: 10,
  },
  bodyCopyForm: {
    fontFamily: 'OpenSans',
    fontSize: 12,
    color: RWBColors.grey,
  },
  filterText: {
    fontFamily: 'OpenSans-Semibold',
    fontSize: 12,
  },
  legalHeader: {
    fontFamily: 'OpenSans',
    textAlign: 'center',
    fontSize: 16,
    color: RWBColors.magenta,
  },
  legalSubheader: {
    fontFamily: 'OpenSans',
    textAlign: 'center',
    fontSize: 16,
    color: RWBColors.navy,
    paddingBottom: 10,
  },
  legalBodyCopy: {
    fontFamily: 'OpenSans',
    fontSize: 12,
    lineHeight: 16,
    color: RWBColors.navy,
    paddingBottom: 10,
  },
  legalBodySection: {
    fontFamily: 'OpenSans-Semibold',
    fontSize: 12,
    lineHeight: 16,
    color: RWBColors.navy,
  },
  link: {
    fontFamily: 'OpenSans-Semibold',
    fontSize: 12,
    lineHeight: 16,
    color: RWBColors.magenta,
  },
  date: {
    fontFamily: 'ChangaOne',
    fontSize: 26,
    lineHeight: 28,
    color: RWBColors.navy,
  },
  navItem: {
    fontFamily: 'OpenSans-Semibold',
    fontSize: 9,
    lineHeight: 11,
  },
  formInput: {
    fontFamily: 'OpenSans',
    fontSize: 12,
    lineHeight: 16,
    top: 2,
    color: 'black',
  },
  formLabel: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 9,
    letterSpacing: 0.2,
    color: RWBColors.grey,
  },
  radioFormLabel: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 9,
    letterSpacing: 0.2,
    color: RWBColors.grey,
    marginBottom: 5,
  },
  errorMessage: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 9,
    lineHeight: 11,
    letterSpacing: 0.2,
    color: RWBColors.magenta,
  },
  errorBar: {
    position: 'absolute',
    left: Dimensions.get('window').width * -0.05,
    top: '-5%',
    backgroundColor: RWBColors.magenta,
    width: 7,
    height: '110%',
  },
  filterCounter: {
    fontFamily: 'ChangaOne',
    fontSize: 10,
    letterSpacing: 0.2,
    color: RWBColors.navy,
  },
  sectionLabelSpacing: {
    marginHorizontal: '5%',
    marginTop: 10,
  },
  // Containers
  registrationScreenContainer: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: RWBColors.white,
  },
  tabScreenContainer: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: RWBColors.white,
  },
  formBlock: {
    marginBottom: 25,
  },
  centerButtonWrapper: {
    width: '100%',
  },
  spinnerOverLay: {
    backgroundColor: 'rgba(255,255,255,0.75)',
    height: '100%',
    width: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  centeredActivityIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButton: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 5,
    paddingBottom: 5,
  },
  headerSave: {
    top: 1,
    paddingRight: 16,
    paddingLeft: 16,
    paddingTop: 5,
    paddingBottom: 5,
  },
  headerSaveText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Bold',
    color: RWBColors.white,
  },
  //Image Styles
  imageContainer: {
    width: '100%',
    height: 150,
    marginBottom: 50,
  },
  coverImageContainer: {
    width: '100%',
  },
  coverImage: {
    width: '100%',
    height: 188,
    backgroundColor: RWBColors.blue, // will be updated to match the blue desired by Dan
  },
  coverEditContainer: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    borderRadius: 8,
    padding: 8,
    backgroundColor: RWBColors.magenta,
  },
  profileImageContainer: {
    position: 'absolute',
    top: 50,
    right: Dimensions.get('window').width * 0.05,
    height: 188,
    width: 188,
    borderRadius: 94,
  },
  profileImage: {
    height: 188,
    width: 188,
    borderRadius: 94,
    borderColor: RWBColors.white,
    borderWidth: 4,
  },
  profileEditContainer: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    borderRadius: 18,
    padding: 8,
    backgroundColor: RWBColors.magenta,
  },
  editImageIcon: {
    height: 20,
    width: 20,
  },
  smallProfileImage: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: RWBColors.white,
    backgroundColor: RWBColors.grey40,
  },
  mediumProfileImage: {
    height: 54,
    width: 54,
    borderRadius: 27,
  },
  chevronBackImage: {
    width: 16,
    height: 16,
  },
  headerIcon: {
    width: 20,
    height: 20,
  },
  // Auto complete styles
  autoAddressBar: {
    borderBottomWidth: 0.25,
    borderColor: RWBColors.grey,
    paddingBottom: 7,
    paddingTop: 10,
    opacity: 0.65,
  },
  autoAddressBarText: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 12,
    lineHeight: 16,
    color: RWBColors.grey,
  },
  // Modal Styles
  modalWindow: {
    flex: 1,
    justifyContent: 'flex-end',
    margin: 25,
    marginTop: 25,
    padding: 16,
    backgroundColor: RWBColors.white,
  },
  scrollArea: {
    flex: 1,
  },
  fixedFooter: {
    flex: 0,
    margin: 0,
    paddingTop: 25,
    paddingHorizontal: 25,
  },
  aboveKeyboard: {
    backgroundColor: RWBColors.magenta,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: 0,
    margin: 0,
    height: 60,
  },
  removeImage: {
    top: 15,
    alignSelf: 'flex-end',
    right: 5,
    zIndex: 2,
    height: 30,
    width: 30,
    borderRadius: 15,
    backgroundColor: RWBColors.magenta,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: RWBColors.white,
  },
  removeImageX: {
    width: 20,
    height: 20,
  },

  // create buttons
  addButtonContainer: {
    position: 'absolute',
    bottom: 50,
    right: 10,
    height: 52,
    width: 52,
    borderRadius: 32,
    shadowOpacity: 0.25,
    shadowRadius: 6,
    shadowColor: 'black',
    shadowOffset: {height: 3, width: 0},
    elevation: 1,
  },
  addButton: {
    backgroundColor: RWBColors.magenta,
    height: 52,
    width: 52,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },

  coverShareButton: {
    position: 'absolute',
    top: 54,
    right: '5%',
    height: 34,
    width: 34,
    borderRadius: 17,
    backgroundColor: RWBColors.whiteOpacity85,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  coverBackButton: {
    position: 'absolute',
    top: 54,
    left: '5%',
    height: 34,
    width: 34,
    borderRadius: 17,
    backgroundColor: RWBColors.whiteOpacity85,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
});
